In [1]:
## Check the single layer perceptron implementation
import sklearn.neural_network as ann
import numpy as np

In [2]:
def genR(N):
    return np.random.random(N)*2-1

def genF(N):
    return np.arange(N)/N+0.001*(genR(N))

N = 20
Ntrain = 5
P = 2
features = np.row_stack([genF(N), genF(N)])
        ##genF(N), genF(N), genF(N),
        ##                 genF(N), genF(N), genF(N), genF(N),
        ##                 genF(N), genF(N), genF(N)])
beta = 0.1*genR(P)
outputs = np.dot(beta, features)

np.savetxt('test_features.dat', features, delimiter='\n')
np.savetxt('test_outputs.dat', outputs, delimiter='\n')

In [37]:
hidden_layer_sizes = (10,)
activation = 'logistic'
solver = 'lbfgs'
alpha = 0.0

slp = ann.MLPRegressor(hidden_layer_sizes, activation,
                       solver, alpha)

slp.fit(features.T[:Ntrain], outputs[:Ntrain])

predictions = slp.predict(features.T)
np.sum((predictions-outputs)**2)

0.00056236463405122145

In [46]:
slp.coefs_

[array([[ 0.36475506,  0.32936209, -0.30034401, -0.03837287, -0.11228597,
         -0.10590716,  0.32378843,  0.1388795 , -0.35671973,  0.3729059 ],
        [ 0.23994701,  0.27131302, -0.27721972,  0.02964724,  0.21391469,
          0.27491315, -0.19445452, -0.3580211 ,  0.07872436, -0.25239263]]),
 array([[-0.23043272],
        [-0.13940985],
        [ 0.01150595],
        [-0.04549845],
        [-0.01995571],
        [ 0.38977472],
        [ 0.02864498],
        [-0.11320513],
        [ 0.02406866],
        [ 0.0843454 ]])]

In [39]:
np.savetxt('test_starting.dat', np.concatenate([slp.coefs_[0].T.flatten(), slp.coefs_[1].flatten()]), delimiter='\n')

In [45]:
predictions

array([-0.00097028, -0.00267174, -0.0043213 , -0.00602068, -0.00765573,
       -0.00936173, -0.01104359, -0.01264567, -0.01425797, -0.01587452,
       -0.01752104, -0.01907509, -0.02066809, -0.02224507, -0.02378155,
       -0.02532156, -0.02677793, -0.02828535, -0.02973809, -0.03117436])

In [44]:
outputs

array([ -6.02201880e-07,  -2.18857264e-03,  -4.31341625e-03,
        -6.51196450e-03,  -8.62829255e-03,  -1.08567235e-02,
        -1.30726768e-02,  -1.51793155e-02,  -1.73220102e-02,
        -1.94815699e-02,  -2.17117739e-02,  -2.38255979e-02,
        -2.60214815e-02,  -2.82167098e-02,  -3.03832150e-02,
        -3.25772855e-02,  -3.46810001e-02,  -3.68906133e-02,
        -3.90508216e-02,  -4.12202709e-02])

In [50]:
slp.coefs_

[array([[ 0.36475506,  0.32936209, -0.30034401, -0.03837287, -0.11228597,
         -0.10590716,  0.32378843,  0.1388795 , -0.35671973,  0.3729059 ],
        [ 0.23994701,  0.27131302, -0.27721972,  0.02964724,  0.21391469,
          0.27491315, -0.19445452, -0.3580211 ,  0.07872436, -0.25239263]]),
 array([[-0.23043272],
        [-0.13940985],
        [ 0.01150595],
        [-0.04549845],
        [-0.01995571],
        [ 0.38977472],
        [ 0.02864498],
        [-0.11320513],
        [ 0.02406866],
        [ 0.0843454 ]])]

In [48]:
slp.intercepts_

[array([ 0.08038026,  0.02153182,  0.08616298,  0.10521527,  0.21466815,
        -0.29889485,  0.37190552, -0.24228942,  0.09181965,  0.06372645]),
 array([ 0.02906137])]

In [75]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(features[0], features[1], outputs)
ax.scatter(features[0], features[1], predictions, color='red')
plt.show()

In [87]:
0.5*(-2.24903e-05+0.000649785+0.00139293+0.0020491+0.00279612)

0.00343272235

In [90]:
0.5*(0.00139293+0.0020491+0.00279612)

0.003119075